[package]
name = "cargo-info"
version = "0.1.0"
authors = ["Nicolai Unrein <n.unrein@gmail.com>"]
edition = "2018"
description = "This extends Cargo to allow you to query your `Cargo.toml` files in a script-friendly way."
license = "Apache-2.0/MIT"
categories = ["command-line-utilities", "config", "development-tools", "development-tools::cargo-plugins", "parsing"]
keywords = ["cli", "cargo", "plugin", "query", "script", "command-line", "tools", "development", "dev-tools"]
readme = "README.md"
repository = "https://github.com/nicolaiunrein/cargo-info"

[dependencies]
cargo_toml = "0.8.1"
clap = "3.0.0-beta.2"
