[package]
name = "cargo_info"
version = "0.1.0"
authors = ["Nicolai Unrein <n.unrein@gmail.com>"]
edition = "2018"
description = "Query package info from Cargo.toml in a script-friendly way."
license = "MIT"
categories = ["Cargo", "cli", "command-line-utilities", "development-tools::cargo-plugins"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.8.1"
clap = "3.0.0-beta.2"
