name: github-actions

on:
  push:
    branches: master

  pull_request:
    branches: master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get package name
        id: cargo-name
        uses: nicolaiunrein/cargo-get@0bf217e108cc09ce06e9e469f961af49415a9608
        with:
          subcommand: package.name
