name: release-on-tag

concurrency:
  group: build-binary-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        run: |
          gh release create ${{ github.ref }} -t ${{ github.ref }} --generate-notes
